include("puzzle-service", "player-service", "puzzle-manager", "scoring-service", "pointer-service", "messages-service")
include("puzzle-service")
include("messages-service")
include("player-service")
include("pointer-service")
include("puzzle-manager")
include("scoring-service")
